// <auto-generated />
namespace EquineNowReloaded.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddHorseListToAuction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHorseListToAuction));
        
        string IMigrationMetadata.Id
        {
            get { return "202105131716346_AddHorseListToAuction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
